// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	entity "git.garena.com/sea-labs-id/bootcamp/batch-02/ziad-rahmatullah/go-robot-simulator-exercise/entity"
	mock "github.com/stretchr/testify/mock"
)

// Mover is an autogenerated mock type for the Mover type
type Mover struct {
	mock.Mock
}

// move provides a mock function with given fields: _a0
func (_m *Mover) move(_a0 *entity.Robot) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewMover interface {
	mock.TestingT
	Cleanup(func())
}

// NewMover creates a new instance of Mover. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMover(t mockConstructorTestingTNewMover) *Mover {
	mock := &Mover{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
